### ISSUE TITLE
Изменение профиля

### ISSUE THREAD

**Issue by binidini** [binidini/binidini#26]
1) После изменения - показывать опять мои настройки
2) radio, checkbox  -- Static_version/form_basic.html   - взять отсюда зеленые  -- см форму создания отправки
3) Показывать  flashes messages
4)необходимо указать желаемый размер, ограничения по формату и размеру для картинки
5) в профиле и настройках (превью) надо одного размера сделать
6) курьер  - индивидуальный,  компания -> юридическое лицо

**Comment by binidini** [comment]
7) {{ form_errors(form.lastName) }}   отсутствует

проверить что для всех полей есть {{ form_errors(form.поле) }}

**Comment by binidini** [comment]
после редактирования вкладки оповещения - оставаться на вкладке оповещение

**Comment by binidini** [comment]
3) Показывать flashes messages   -сделано

**Comment by allnimator** [comment]
7, 3, 6 - завершена

**Comment by binidini** [comment]
все сделано кроме 1), сделал отдельный таск
