### ISSUE TITLE
Апи поиска заказов

### ISSUE THREAD

**Issue by allnimator** [binidini/binidini#78]
Нужен апи-метод, по которому можно получить доступные для заказа заказы.
Получить заказы можно по адресу, по нечетко заданному адресу, по адресу заданным с ошибкой, по координатам.
Заказы надо сортировать по удаленности от запрашиваемой точки

**Comment by binidini** [comment]
сделал 
http://tytymyty/app_dev.php/shipment/search?top-search=%D0%BC%D0%BE%D1%81%D0%BA%D0%B2%D0%B0&_format=json
