### ISSUE TITLE
Апи-поиска

### ISSUE THREAD

**Issue by allnimator** [binidini/binidini#85]
Я сделал роут binidini_api_search_shipment_search
Туда передаю параметр top-search. Например: http://tytymyty/app_dev.php/api/shipments/search?top-search=Пушкин&access_token=N2QxMGFhYTY5ODNkNGY4MzAxOTlkZDYzYjA3YTdkMmI3NDUwYThiMjc4MTQwMDkwMDVjZTNkOTQ1NDA4MTg1ZQ
Контроллер правильно подхватывает параметр, но ищет неверно.
Например на сайте https://www.dropbox.com/s/x8crfv8bjmhr40h/Screenshot%202015-07-02%2018.18.46.png?dl=0
В апи выдает просто сортированный по id список.
Надо эту проблему поправить

**Comment by binidini** [comment]
сделано - в гтите
