### ISSUE TITLE
Апи для обновление профиля

### ISSUE THREAD

**Issue by allnimator** [binidini/binidini#93]
Проблема. При PUT - запросе на api/user/{id} выдается https://www.dropbox.com/s/dy3f242wfxuk5xl/Screenshot%202015-07-30%2015.19.33.png?dl=0

Запрос PUT: email=allnimator%40gmail.com&access_token=MzEzNTY1MzY2OGVlZTE1ODRkY2I5NWZkMzMxZmEwNzhhZmUxNTQ2ZmNkZTViNWQwZjFiNGM0NzZjMWY4Y2I4ZQ
http://dev.tytymyty.ru/app_dev.php/api/users/1

https://www.dropbox.com/s/sxvzkmsecir2d78/Screenshot%202015-07-30%2015.20.16.png?dl=0

В роутинге на этот роут указан resource bundle. Он не находит необходимые геттеры. В вебе с этим разбирается fos user bundle. Но он, бляха, не понимает апи-запросы и возвращает html. И нет в нем логики такой. При регистрации пользователя я решил эту проблему создав RegistrationController. Надо такое же сделать для обновления

**Comment by allnimator** [comment]
Может мое решение и не верно, но другое быстрое я не нашел

**Comment by allnimator** [comment]
В ответе надо возвращать обновленную сущность, чтобы мне еще раз не запрашивать пользователя, либо ошибочный код

**Comment by allnimator** [comment]
Денис, проверь загрузку фотографии по апи. Я не нашел способ обновить ее через апи. Ни отправка файла, ни кодировка бэйс 64 не работает.

**Comment by binidini** [comment]
Обновил  Form/Type/UserType 
Там была только email  - надеюсь все заработает теперь
