### ISSUE TITLE
При переходе с платежной системы отображается логин-скрин

### ISSUE THREAD

**Issue by allnimator** [binidini/binidini#96]
https://www.dropbox.com/s/ebhmatqo809dyc9/Screenshot%202015-08-10%2018.13.43.png?dl=0

Платеж не отмечается как оплачен, а деньги на счет пользователя не добавляются. Это возможно и в обычных браузерах. Достаточно, чтобы вырубило интернет или при медленном соединение или же пользователь закроет вкладку.

Надо сделать выставление статуса оплачен/зафейлен через воркер. Посылать запрос пока не завершится платеж.
Переход на саксес не означает успеха при платеже. Не обработан кейс, когда статус платежа на стороне платежной системы будет "процессинг". То есть пользователь перешел, а платеж не обработан до конца - деньги пользователь теряет.

**Comment by binidini** [comment]
теперь платеж обрабатывается и перекидывает на логин страницу  с сообщением о статусе платежа.

Воркер надо будет также добавить - добавлю задачу на себя
